before_script:
  - docker info
  - '[ -d tmp ] || mkdir tmp'
  - git clone https://github.com/OSC/ondemand-packaging.git tmp/ondemand-packaging
  - cp /systems/osc_certs/gpg/ondemand/.gpgpass $CI_PROJECT_DIR/tmp/ondemand-packaging/
  - cp /systems/osc_certs/gpg/ondemand/ondemand.sec $CI_PROJECT_DIR/tmp/ondemand-packaging/
stages:
  - build_and_deploy

rpm-build_and_deploy:
  variables:
    RLS_SCRIPT: "./tmp/ondemand-packaging/release.py"
    RLS_KEY: "/systems/osc_certs/ssh/ondemand-packaging/id_rsa"
    RLS_OUTPUT: "./tmp/output/*"
    SECTION: "main"
  stage: build_and_deploy
  only:
    - tags
  script:
    - if [[ "$CI_COMMIT_TAG" =~ .*_.* ]]; then export SECTION=ci; fi
    - (./tmp/ondemand-packaging/build.sh -w $CI_PROJECT_DIR/tmp/work -o $CI_PROJECT_DIR/tmp/output -V $CI_COMMIT_TAG -u $CI_PROJECT_DIR/packaging) && ($RLS_SCRIPT --pkey $RLS_KEY -c $SECTION $RLS_OUTPUT) || echo "Fail!"
