#
# == Shell App ==
#
# This is an example configuration file for the Shell App. To configure the
# Shell App for a given OnDemand portal, you would copy this file to the
# following location:
#
#     /etc/ood/config/apps/shell/config.yml
#
# on the OnDemand host machine and modify it.
#

---
# The default SSH host the user is logged into if the user doesn't specify a
# host in the URL
#
#default_host: "localhost"
