# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65cfaa1998a4d84d12f4e463bf5d040b9bf073eab4427c4cb20d98ed6a3edc5c97a99b527fcb60526d6dc13c5f46ca942ebb83fe4802a5a967aa26644c7ca25c

test:
  secret_key_base: 301c9d80afa32f7d33f59027aab70840e290829a25b0c8fb6107b258ff8a0f134d438adb10b843ba049a5fea9fb150af5d14fba86a22f81faf191102c660d17e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
