name: Audit Dependencies

on:
  schedule:
    # Run every day
    #
    # https://crontab.guru/#0_0_*_*_*
    #
    - cron: '0 0 * * *'

jobs:
  audit-dependencies:
    steps:
      # Install Ruby and Bundler
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5.5
          bundler: 1.17.3
      # Install Node
      - uses: actions/setup-node@v1

      # Install yarn
      - name: Install audit dependencies
        run: |
          npm install -g yarn

      # Checkout Repo
      - name: Checkout OSC/ondemand@master
        uses: actions/checkout@v2
        with:
          repository: 'OSC/ondemand'
          ref: 'master'

      # Run Rake task
      - name: Run rake audit:dependencies
        run: |
          rake audit:dependencies
