name: Issue Lifecycle

# Run this action when an issue is opened
on:
  issues:
    types: [opened]

jobs:
  # If the created issue does not have a milestone attached to it, assign the issue to the backlog
  assign-milestone:
    runs-on: ubuntu-latest
    steps:
      - name: Assign the created issue to the backlog milestone if no milestone is defined.
        if: github.event.issue.milestone == null
        # Set environment
        env:
          MILESTONE_ID: 5
        run: |
          curl --silent --output /dev/null --request PATCH \
          --url https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
              "milestone": "'$MILESTONE_ID'"
            }'
