# 
name: Pull Request Labeler
on:
  workflow_dispatch:
  pull_request:

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@main
      with:
        repo-token: ${{ secrets.OSCWIAG_ISSUE_TOKEN }}
        configuration-path: .github/labeler.yml
        sync-labels: true # Revert the labels applied to the PR when changes are reverted.